"""create tickets table

Revision ID: 3ba408c1afc7
Revises: 
Create Date: 2026-07-01 20:09:45.024997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ba408c1afc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticketpriority'), nullable=False),
    sa.Column('assignee', sa.String(length=200), nullable=True),
    sa.Column('raw_source_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_source_id'), 'tickets', ['source_id'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_source_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
